// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckSelectAllController from "./check_select_all_controller"
application.register("check-select-all", CheckSelectAllController)

import CheckboxSelectAllController from "./checkbox_select_all_controller"
application.register("checkbox-select-all", CheckboxSelectAllController)

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import DomainTableController from "./domain_table_controller"
application.register("domain-table", DomainTableController)

import FeedPathSelectController from "./feed_path_select_controller"
application.register("feed-path-select", FeedPathSelectController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import ShowhideController from "./showhide_controller"
application.register("showhide", ShowhideController)
