// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import DomainTableController from "./domain_table_controller"
application.register("domain-table", DomainTableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)