domain_update_job:
  cron: "*/5 * * * *" 
  name: "Update Job"
  class: "DomainUpdateJob"
  queue: default


update_feedzone_job:
  cron: "*/6 * * * *" 
  name: "Update Feedzone Job"
  class: "UpdateFeedzoneJob"
  queue: default
